@startuml

enum Content {
   VIDEO
   AUDIO
}

enum Level {
  GRUNDKURS
  BRONZE
  SILBER
  GOLD
  GOLDSTAR
  TOPCLASS
}


class Course {
  String: type
  Content: content
  Level: level
}

class File

class User {
  Long: id
}

Course  <-up-  Level: gehört zu
Course  <-down-  Content: hat

@enduml
