@startuml
left to right direction

        actor TanschuelerIn
        actor Tanzschule

        rectangle online-dancing-practice {

        TanschuelerIn -- (wählt den Kurs und das Level)
        TanschuelerIn -- (schaut Tanzvideos)
        TanschuelerIn -- (hört Lieder )
        Tanzschule -- (betrachtet Nutzungsdaten)
        Tanzschule -- (legt neue Kurse an)
        Tanzschule -- (lädt Files hoch)
        Tanzschule -- (ordnet Files Kursen zu)
        }
@enduml
