GET http://localhost:8080/api/file
Accept: application/json

###


GET http://localhost:8080/api/file/6
Accept: application/json


####
POST localhost:8080/api/file/create
Content-Type: application/json

{
  "name": "File123",
  "path": "example/path/123",
  "contentType": "VIDEO"
}


######

DELETE http://localhost:8080/api/file/6
Accept: application/json

###

GET http://localhost:8080/api/level
Accept: application/json


#####
POST http://localhost:8080/api/level/create
Content-Type: application/json

{
    "id": "AH",
    "description": "bahahaha"
}


###

GET http://localhost:8080/api/level/AH
Accept: application/json

####

DELETE http://localhost:8080/api/level/AH
Accept: application/json


####

GET http://localhost:8080/api/usage
Accept: application/json

####


GET http://localhost:8080/api/usage/2
Accept: application/json

####

POST http://localhost:8080/api/usage/create
Content-Type: application/json

{
  "course": {
    "title": "Latein",
    "description": "Kurs für Anfänger",
    "level": {
      "id": "1",
      "description": "bahahaha"
    }
  },
  "file": {
  "name": "File123",
  "path": "example/path/123",
  "contentType": "VIDEO"
  }
}


####

DELETE http://localhost:8080/api/usage/2
Accept: application/json
