= Inhaltsangabe
:sectnums:

== Ausgangslage
In tanzschulen werden x Schüler unterrichtet. Es gibt xx Tanzschulen.

== Ist Zustand
Traditionellerweise wird vor Ort unterrichtet,

== Problemstellung
In Zeiten der Pandemie werden Tanzschulen geschlossen und die Kundenbindung geht verloren

== Aufgabenstellung
Durch Erstelleung eines Tanz-Video-Portals kann die Tanzschule die Kommunikation mit ihren Kunden aufrechterhalten.
Auch wenn die Tanzschule wieder geöffnet ist,  können die Kunden der Tanzschule das Tanzportal benutzen um zuhause
die gelernten Tnazschritte sich nocmal anzusehen und als grundlage für ihre Übungseinheiten.

Man muss beachten das beachten das man sich selbst keine konkurenz macht -> deswegen gibt es einen zugangscode mithilfe dessen man die videos dann benutzten kann.

== Systemarchitekur und Entwurf

* Schnittstellenbeschreibung mit Swagger (mit link)

== Verwendete Technnologien
=== Projektorganisation (Youtrack, Git)

== Ausgewählte Aspekte

=== Besondere Codestellen
Authentication

=== Probleme

Fileupload, Cors, Deployment,




== Deployment

* gh-actions
* pipeline ci/cd (continuous integrations)

== Conclusio

Wie ist es gegangen, Welche Fehler, Selbstreflexion

== Anhang

=== Protokolle

=== Arbeitsaufteilung

* Wer was gemacht hat?

=== Lieferumfang für Kunde:
* Gitrepository
* Bedienunganleitung(Gh-pages, Wie man es bedient es?)
* Systemdoku(Systemarchitekur)

==== Lieferumfang für Lehrer:





