  name: Quarkus Codestart CI

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
        # Step that does that actual cache save and restore
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: start Postgres
          working-directory: backend/src/main/docker/
          run: docker-compose up -d
        - name: Build
          run: mvn package -B
          working-directory: backend

        - name: install ssh key
          uses: webfactory/ssh-agent@v0.4.1
          with:
           ssh-private-key: ${{ secrets.ONLINE_DANCE_PRACTICE }}
        - name: create .ssh/known_hosts
          run: |
              ssh-keyscan -H -t rsa -v ${{ secrets.ONLINE_DANCE_PRACTICE_IP }}  >> ~/.ssh/known_hosts
